import './globals.css'

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = () => ({
    children,
}) => {
    
    return (
        
        <html lang="en">
            
            <body className="">
                {children}
            </body>
        </html>
        
    )
    
}

export default RootLayout
